version: "3.8"
networks:
  receita_network:
volumes:
  receita_volume:

services:
  db:
    image: postgres:13-alpine
    volumes:
      - receita_volume:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=receita
      - POSTGRES_PASSWORD=receita
    ports:
      - "5432:5432"
    networks:
      - receita_network
    command: >
      -c work_mem=32MB
      -c maintenance_work_mem=64MB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U receita" ]
      interval: 2s
      timeout: 2s
      retries: 3
    deploy:
      resources:
        limits:
          memory: "252M"
          cpus: '0.5'

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - receita_network
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - ./data:/data
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: "400M"
          cpus: '0.5'